### ISSUE TITLE
o2o_comments_cnn.model

### ISSUE THREAD

**Issue by w2486696** [HanlynnKe/nlp-demo#1]
没有这个文件

**Comment by HanlynnKe** [comment]
> 没有这个文件

这个其实是代码跑完生成的，仓库里没有吗

**Comment by HanlynnKe** [comment]
> > 没有这个文件
> 
> 这个其实是代码跑完生成的，仓库里没有吗

我添加一下好了

**Comment by HanlynnKe** [comment]
> 没有这个文件

 train_CNN.py跑一下就会有的。我上传了CNN的word2vec模型，RNN超过25MB不让我传 :-<
